# Generated by Django 5.1.1 on 2024-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='direcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='razon_social',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='representante_legal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='vehiculo_asociado',
            field=models.CharField(max_length=200),
        ),
    ]
