# Generated by Django 5.1.1 on 2024-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_alter_proveedores_direcion_alter_proveedores_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='nit',
            field=models.CharField(max_length=10),
        ),
    ]
